# PostgreSQL. Versions 9.6 and up are supported.
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_production") %>

cable:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_production") %>

queue:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_production") %>

cache:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_production") %>
